from PyQt5 import QtCore, QtGui, QtWidgets
from ui_methed_test import *
import threading
import random
import datetime
import time
import data_filter
import sys


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.connect_button = QtWidgets.QPushButton(self.centralwidget)
        self.connect_button.setObjectName("connect_button")
        self.verticalLayout_4.addWidget(self.connect_button)
        self.lcdNumber = QtWidgets.QLCDNumber(8, self.centralwidget)
        self.lcdNumber.setObjectName("lcdNumber")
        self.verticalLayout_4.addWidget(self.lcdNumber)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.status_label = QtWidgets.QLabel(self.centralwidget)
        self.status_label.setObjectName("status_label")
        self.horizontalLayout.addWidget(self.status_label)
        self.ticker_table = QtWidgets.QTableWidget(self.centralwidget)
        self.ticker_table.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ticker_table.setAutoFillBackground(False)
        self.ticker_table.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        self.ticker_table.setObjectName("ticker_table")
        self.ticker_table.setColumnCount(7)
        self.ticker_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.ticker_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ticker_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ticker_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ticker_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ticker_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ticker_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.ticker_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.ticker_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.ticker_table.setItem(0, 0, item)
        self.horizontalLayout.addWidget(self.ticker_table)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)
        self.horizontalLayout.setStretch(2, 9)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.depth_tab = QtWidgets.QWidget()
        self.depth_tab.setObjectName("depth_tab")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.depth_tab)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.depth_label_1 = QtWidgets.QLabel(self.depth_tab)
        self.depth_label_1.setObjectName("depth_label_1")
        self.verticalLayout_5.addWidget(self.depth_label_1)
        self.depth_table_1 = QtWidgets.QTableWidget(self.depth_tab)
        self.depth_table_1.setObjectName("depth_table_1")
        self.depth_table_1.setColumnCount(4)
        self.depth_table_1.setRowCount(20)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_1.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_1.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_1.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_1.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_1.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_1.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_1.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_1.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_1.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_1.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_1.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_1.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_1.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_1.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_1.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_1.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_1.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_1.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_1.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_1.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_1.setHorizontalHeaderItem(3, item)
        self.verticalLayout_5.addWidget(self.depth_table_1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.depth_label_2 = QtWidgets.QLabel(self.depth_tab)
        self.depth_label_2.setObjectName("depth_label_2")
        self.verticalLayout_7.addWidget(self.depth_label_2)
        self.depth_table_2 = QtWidgets.QTableWidget(self.depth_tab)
        self.depth_table_2.setObjectName("depth_table_2")
        self.depth_table_2.setColumnCount(4)
        self.depth_table_2.setRowCount(20)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_2.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_2.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_2.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_2.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_2.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_2.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_2.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_2.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_2.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_2.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_2.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_2.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_2.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_2.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.depth_table_2.setHorizontalHeaderItem(3, item)
        self.verticalLayout_7.addWidget(self.depth_table_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_11.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.depth_tab, "")
        self.trades_tab = QtWidgets.QWidget()
        self.trades_tab.setObjectName("trades_tab")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.trades_tab)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.trades_label_1 = QtWidgets.QLabel(self.trades_tab)
        self.trades_label_1.setObjectName("trades_label_1")
        self.verticalLayout_6.addWidget(self.trades_label_1)
        self.trades_table_1 = QtWidgets.QTableWidget(self.trades_tab)
        self.trades_table_1.setObjectName("trades_table_1")
        self.trades_table_1.setColumnCount(5)
        self.trades_table_1.setRowCount(20)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_1.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_1.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_1.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_1.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_1.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_1.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_1.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_1.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_1.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_1.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_1.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_1.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_1.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_1.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_1.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_1.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_1.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_1.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_1.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_1.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_1.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_1.setHorizontalHeaderItem(4, item)
        self.verticalLayout_6.addWidget(self.trades_table_1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.trades_label_2 = QtWidgets.QLabel(self.trades_tab)
        self.trades_label_2.setObjectName("trades_label_2")
        self.verticalLayout_8.addWidget(self.trades_label_2)
        self.trades_table_2 = QtWidgets.QTableWidget(self.trades_tab)
        self.trades_table_2.setObjectName("trades_table_2")
        self.trades_table_2.setColumnCount(5)
        self.trades_table_2.setRowCount(20)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_2.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_2.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_2.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_2.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_2.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_2.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_2.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_2.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_2.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_2.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_2.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_2.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_2.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_2.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table_2.setHorizontalHeaderItem(4, item)
        self.verticalLayout_8.addWidget(self.trades_table_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout_12.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.trades_tab, "")
        self.kline_tab = QtWidgets.QWidget()
        self.kline_tab.setObjectName("kline_tab")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.kline_tab)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.kline_label = QtWidgets.QLabel(self.kline_tab)
        self.kline_label.setObjectName("kline_label")
        self.verticalLayout_9.addWidget(self.kline_label)
        self.kline_table = QtWidgets.QTableWidget(self.kline_tab)
        self.kline_table.setAutoScroll(True)
        self.kline_table.setAutoScrollMargin(16)
        self.kline_table.setShowGrid(True)
        self.kline_table.setGridStyle(QtCore.Qt.SolidLine)
        self.kline_table.setWordWrap(True)
        self.kline_table.setCornerButtonEnabled(True)
        self.kline_table.setObjectName("kline_table")
        self.kline_table.setColumnCount(6)
        self.kline_table.setRowCount(40)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setVerticalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setVerticalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setVerticalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setVerticalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setVerticalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setVerticalHeaderItem(30, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setVerticalHeaderItem(31, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setVerticalHeaderItem(32, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setVerticalHeaderItem(33, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setVerticalHeaderItem(34, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setVerticalHeaderItem(35, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setVerticalHeaderItem(36, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setVerticalHeaderItem(37, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setVerticalHeaderItem(38, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setVerticalHeaderItem(39, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.kline_table.setHorizontalHeaderItem(5, item)
        self.verticalLayout_9.addWidget(self.kline_table)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.tabWidget.addTab(self.kline_tab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 9)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.my_setting()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.connect_button.setText(_translate("MainWindow", "连接"))
        self.status_label.setText(_translate("MainWindow", "状态："))
        item = self.ticker_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "BTC"))
        item = self.ticker_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "交易时间"))
        item = self.ticker_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "买入价(￥)"))
        item = self.ticker_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "卖出价(￥)"))
        item = self.ticker_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "今日最高(￥)"))
        item = self.ticker_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "今日最低(￥)"))
        item = self.ticker_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "最新(￥)"))
        item = self.ticker_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "成交量(฿)"))
        __sortingEnabled = self.ticker_table.isSortingEnabled()
        self.ticker_table.setSortingEnabled(False)
        self.ticker_table.setSortingEnabled(__sortingEnabled)
        self.depth_label_1.setText(_translate("MainWindow", "最新市场深度 0.01"))
        item = self.depth_table_1.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.depth_table_1.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.depth_table_1.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.depth_table_1.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.depth_table_1.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.depth_table_1.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.depth_table_1.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.depth_table_1.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.depth_table_1.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.depth_table_1.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.depth_table_1.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "11"))
        item = self.depth_table_1.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "12"))
        item = self.depth_table_1.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "13"))
        item = self.depth_table_1.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "14"))
        item = self.depth_table_1.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "15"))
        item = self.depth_table_1.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "16"))
        item = self.depth_table_1.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "17"))
        item = self.depth_table_1.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "18"))
        item = self.depth_table_1.verticalHeaderItem(18)
        item.setText(_translate("MainWindow", "19"))
        item = self.depth_table_1.verticalHeaderItem(19)
        item.setText(_translate("MainWindow", "20"))
        item = self.depth_table_1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "买入价(￥)"))
        item = self.depth_table_1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "委单量(฿)"))
        item = self.depth_table_1.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "卖出价(￥)"))
        item = self.depth_table_1.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "委单量(฿)"))
        self.depth_label_2.setText(_translate("MainWindow", "显示时间：00：00：00"))
        item = self.depth_table_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "21"))
        item = self.depth_table_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "22"))
        item = self.depth_table_2.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "23"))
        item = self.depth_table_2.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "24"))
        item = self.depth_table_2.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "25"))
        item = self.depth_table_2.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "26"))
        item = self.depth_table_2.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "27"))
        item = self.depth_table_2.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "28"))
        item = self.depth_table_2.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "29"))
        item = self.depth_table_2.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "30"))
        item = self.depth_table_2.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "31"))
        item = self.depth_table_2.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "32"))
        item = self.depth_table_2.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "33"))
        item = self.depth_table_2.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "34"))
        item = self.depth_table_2.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "35"))
        item = self.depth_table_2.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "36"))
        item = self.depth_table_2.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "37"))
        item = self.depth_table_2.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "38"))
        item = self.depth_table_2.verticalHeaderItem(18)
        item.setText(_translate("MainWindow", "39"))
        item = self.depth_table_2.verticalHeaderItem(19)
        item.setText(_translate("MainWindow", "40"))
        item = self.depth_table_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "买入价(￥)"))
        item = self.depth_table_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "委单量(฿)"))
        item = self.depth_table_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "卖出价(￥)"))
        item = self.depth_table_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "委单量(฿)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.depth_tab), _translate("MainWindow", "市场深度"))
        self.trades_label_1.setText(_translate("MainWindow", "最新交易记录"))
        item = self.trades_table_1.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.trades_table_1.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.trades_table_1.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.trades_table_1.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.trades_table_1.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.trades_table_1.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.trades_table_1.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.trades_table_1.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.trades_table_1.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.trades_table_1.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.trades_table_1.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "11"))
        item = self.trades_table_1.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "12"))
        item = self.trades_table_1.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "13"))
        item = self.trades_table_1.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "14"))
        item = self.trades_table_1.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "15"))
        item = self.trades_table_1.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "16"))
        item = self.trades_table_1.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "17"))
        item = self.trades_table_1.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "18"))
        item = self.trades_table_1.verticalHeaderItem(18)
        item.setText(_translate("MainWindow", "19"))
        item = self.trades_table_1.verticalHeaderItem(19)
        item.setText(_translate("MainWindow", "20"))
        item = self.trades_table_1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "交易时间"))
        item = self.trades_table_1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "交易序号"))
        item = self.trades_table_1.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "成交价格(￥)"))
        item = self.trades_table_1.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "成交量(฿)"))
        item = self.trades_table_1.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "买卖类型"))
        self.trades_label_2.setText(_translate("MainWindow", "显示时间：00：00：00"))
        item = self.trades_table_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "21"))
        item = self.trades_table_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "22"))
        item = self.trades_table_2.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "23"))
        item = self.trades_table_2.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "24"))
        item = self.trades_table_2.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "25"))
        item = self.trades_table_2.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "26"))
        item = self.trades_table_2.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "27"))
        item = self.trades_table_2.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "28"))
        item = self.trades_table_2.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "29"))
        item = self.trades_table_2.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "30"))
        item = self.trades_table_2.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "31"))
        item = self.trades_table_2.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "32"))
        item = self.trades_table_2.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "33"))
        item = self.trades_table_2.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "34"))
        item = self.trades_table_2.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "35"))
        item = self.trades_table_2.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "36"))
        item = self.trades_table_2.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "37"))
        item = self.trades_table_2.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "38"))
        item = self.trades_table_2.verticalHeaderItem(18)
        item.setText(_translate("MainWindow", "39"))
        item = self.trades_table_2.verticalHeaderItem(19)
        item.setText(_translate("MainWindow", "40"))
        item = self.trades_table_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "交易时间"))
        item = self.trades_table_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "交易序号"))
        item = self.trades_table_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "成交价格(￥)"))
        item = self.trades_table_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "成交量(฿)"))
        item = self.trades_table_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "买卖类型"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.trades_tab), _translate("MainWindow", "交易记录"))
        self.kline_label.setText(_translate("MainWindow", "K线数据~~~~~~~"))
        self.kline_table.setSortingEnabled(False)
        item = self.kline_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.kline_table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.kline_table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.kline_table.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.kline_table.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.kline_table.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.kline_table.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.kline_table.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.kline_table.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.kline_table.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.kline_table.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "11"))
        item = self.kline_table.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "12"))
        item = self.kline_table.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "13"))
        item = self.kline_table.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "14"))
        item = self.kline_table.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "15"))
        item = self.kline_table.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "16"))
        item = self.kline_table.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "17"))
        item = self.kline_table.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "18"))
        item = self.kline_table.verticalHeaderItem(18)
        item.setText(_translate("MainWindow", "19"))
        item = self.kline_table.verticalHeaderItem(19)
        item.setText(_translate("MainWindow", "20"))
        item = self.kline_table.verticalHeaderItem(20)
        item.setText(_translate("MainWindow", "21"))
        item = self.kline_table.verticalHeaderItem(21)
        item.setText(_translate("MainWindow", "22"))
        item = self.kline_table.verticalHeaderItem(22)
        item.setText(_translate("MainWindow", "23"))
        item = self.kline_table.verticalHeaderItem(23)
        item.setText(_translate("MainWindow", "24"))
        item = self.kline_table.verticalHeaderItem(24)
        item.setText(_translate("MainWindow", "25"))
        item = self.kline_table.verticalHeaderItem(25)
        item.setText(_translate("MainWindow", "26"))
        item = self.kline_table.verticalHeaderItem(26)
        item.setText(_translate("MainWindow", "27"))
        item = self.kline_table.verticalHeaderItem(27)
        item.setText(_translate("MainWindow", "28"))
        item = self.kline_table.verticalHeaderItem(28)
        item.setText(_translate("MainWindow", "29"))
        item = self.kline_table.verticalHeaderItem(29)
        item.setText(_translate("MainWindow", "30"))
        item = self.kline_table.verticalHeaderItem(30)
        item.setText(_translate("MainWindow", "31"))
        item = self.kline_table.verticalHeaderItem(31)
        item.setText(_translate("MainWindow", "32"))
        item = self.kline_table.verticalHeaderItem(32)
        item.setText(_translate("MainWindow", "33"))
        item = self.kline_table.verticalHeaderItem(33)
        item.setText(_translate("MainWindow", "34"))
        item = self.kline_table.verticalHeaderItem(34)
        item.setText(_translate("MainWindow", "35"))
        item = self.kline_table.verticalHeaderItem(35)
        item.setText(_translate("MainWindow", "36"))
        item = self.kline_table.verticalHeaderItem(36)
        item.setText(_translate("MainWindow", "37"))
        item = self.kline_table.verticalHeaderItem(37)
        item.setText(_translate("MainWindow", "38"))
        item = self.kline_table.verticalHeaderItem(38)
        item.setText(_translate("MainWindow", "39"))
        item = self.kline_table.verticalHeaderItem(39)
        item.setText(_translate("MainWindow", "40"))
        item = self.kline_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "交易时间"))
        item = self.kline_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "开盘价(￥)"))
        item = self.kline_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "最高价(￥)"))
        item = self.kline_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "最低价(￥)"))
        item = self.kline_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "收盘价(￥)"))
        item = self.kline_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "成交量(฿)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.kline_tab), _translate("MainWindow", "K线数据"))

    def __init__(self):
        self.ticker = {'data': {'timestamp': 0, 'buy': 0, 'sell': 0, 'high': 0, 'low': 0, 'last': 0, 'vol': 0},
                       'update': {'now_time': 0, 'timestamp_update': False, 'buy_update': False, 'sell_update': False,
                                  'high_update': False, 'low_update': False, 'last_update': False, 'vol_update': False},
                       'send_rest': True, 'last_time': 0}

        self.depth = dict()
        self.depth['send_rest'] = True
        self.depth['now_time'] = 0
        self.depth['asks'] = list()
        self.depth['bids'] = list()
        for i in range(60):
            temp = dict()
            temp['l'] = [0.0, 0.0]
            temp['timestamp'] = 0
            self.depth['asks'].append(temp)
        for i in range(60):
            temp = dict()
            temp['l'] = [0.0, 0.0]
            temp['timestamp'] = 0
            self.depth['bids'].append(temp)

        self.trades = {'data': [], 'send_rest': True, 'now_time': 0}
        for i in range(60):
            temp = {'tid': 0, 'price': 0, 'amount': 0, 'timestamp': 0, 'type': 'NULL'}
            self.trades['data'].append(temp)

        self.kline = {'data': [], 'send_rest': True, 'now_time': 0, 'update': False}
        for i in range(40):
            temp = {'timestamp': 0, 'open': 0, 'high': 0, 'low': 0, 'close': 0, 'vol': 0}
            self.kline['data'].append(temp)

    def my_setting(self):
        self.connect_button.clicked.connect(self.to_connect)
        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.change_time)
        self.depth_timer = QtCore.QTimer()
        self.depth_timer.timeout.connect(self.change_depth_table)
        self.trades_timer = QtCore.QTimer()
        self.trades_timer.timeout.connect(self.change_trades_table)
        self.kline_timer = QtCore.QTimer()
        self.kline_timer.timeout.connect(self.change_kline_table)

    def change_kline_table(self):
        print('触发 kline 时钟')
        self.kline_label.setText('K线数据 1分钟间隔 显示时间： %s' % str(datetime.datetime.now()))
        update_kline_table(self)

    def change_trades_table(self):
        print('触发 trades 时钟')
        self.trades_label_2.setText('显示时间： %s' % str(datetime.datetime.now()))
        update_trades_table(self)

    def change_depth_table(self):
        print('触发 depth 时钟')
        self.depth_label_2.setText('显示时间： %s' % str(datetime.datetime.now()))
        update_depth_table(self)

    def change_time(self):
        self.status_label.setText(str(datetime.datetime.now()))

        current_time = QtCore.QTime.currentTime()
        self.lcdNumber.display(current_time.toString('HH:mm:ss'))

        print('触发 ticker 时钟')
        update_ticker_table(self)

    def to_connect(self):
        ui_thread_websocket_start(self)
        self.timer.start(1000)
        self.depth_timer.start(500)
        self.trades_timer.start(500)
        self.kline_timer.start(1000)

    def closeEvent(self, event):
        self.timer.stop()
        self.depth_timer.stop()
        self.trades_timer.stop()
        self.kline_timer.stop()
        # okcoin_websocket.ws.close()
        # # 关闭窗口的事件触发消息框询问，并设置消息框标题，提示信息，选择按键
        # reply = QtGui.QMessageBox.question(self, 'Message',
        #                                    "Are you sure to quit?", QtGui.QMessageBox.Yes, QtGui.QMessageBox.No)
        #
        # if reply == QtGui.QMessageBox.Yes:
        #     event.accept()
        # else:
        #     event.ignore()


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
